[package]
name = "one_error"
version = "0.0.1"
edition = "2021"
documentation = "https://docs.rs/one_error/"
description = "ergonomic and precise error handling built atop type-level set arithmetic and stack context"
license = "Apache-2.0"
repository = "https://github.com/mcmah309/one_error"
categories = ["rust-patterns"]
keywords = ["error", "error-handling", "type-level", "anonymous", "sum"]
readme = "README.md"