[package]
name = "eros"
version = "0.0.5"
edition = "2021"
documentation = "https://docs.rs/eros/"
description = "Context aware, ergonomic and precise error handling."
license = "Apache-2.0"
repository = "https://github.com/mcmah309/eros"
categories = ["rust-patterns"]
keywords = ["error", "error-handling"]
readme = "README.md"

[dev-dependencies]
anyhow="1"